### ISSUE TITLE
feature request: download & upload json file through browser

### ISSUE THREAD

**Issue by amn41** [azazdeaz/rasa-nlu-trainer#2]
As far as I could tell, we could make this a completely standalone/ offline-friendly app if the user could upload & download json files, correct? 

I ask because this would let non-technical people (who wouldn't run a node server on their machine) use create training data just by going to a URL

**Comment by azazdeaz** [comment]
Yes, definitely! I will add this as soon as i can :)

**Comment by amn41** [comment]
Cool! I'm also happy to help out

**Comment by azazdeaz** [comment]
Thanks, i just updated the online version with upload/download buttons :) 👍
