### ISSUE TITLE
Demo doesn't work in Firefox

### ISSUE THREAD

**Issue by andreapavoni** [azazdeaz/rasa-nlu-trainer#4]
I've tried this demo on Firefox, my browser of choice, and noted that it doesn't work.

* For some reason, JS throws an error in `JSON.parse`
* When I highlight a word from a text phrase it doesn't activate the button to create a new entity (perhaps because of the previous error)

Tried in Chrome, it works as expected.

**Comment by azazdeaz** [comment]
Hi @andreapavoni ! 
Unfortunately, Firefox doesn't support the selectionchange event properly at the moment (which is crucial for the entity selection) http://caniuse.com/#feat=selection-api
I've tried some polyfills with no luck, so please use an other browser until Firefox adds support.

Of course, contributions are welcomed :)

**Comment by azazdeaz** [comment]
continue in https://github.com/golastmile/rasa-nlu-trainer/issues/12
