### ISSUE TITLE
Unhandled Promise Rejection

### ISSUE THREAD

**Issue by prasanna-bigreco** [azazdeaz/rasa-nlu-trainer#9]
I am getting unhandled promise rejection upon starting this. 

My command in the examples/rasa directory is -
**sudo rasa-nlu-trainer --source demo-rasa.json**

This errors out saying 
**(node:18769) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): "rasa_nlu_data.common_examples" is undefined**

I see this if loop in server.js

if (!json.rasa_nlu_data.common_examples) {
        return reject('"rasa_nlu_data.common_examples" is undefined')
      }

Can you please help?

**Comment by azazdeaz** [comment]
Hi, i just updated the npm package (v0.2.4). It should handle this case 👍

**Comment by prasanna-bigreco** [comment]
hey looks cool. thank you.
